### PR TITLE
[PKG-3123] nfoursid v1.0.1 ❄️

### PR DESCRIPTION
**Pull request by lorepirri**
[PKG-3123] nfoursid v1.0.1 ❄️

destination channel: **Snowflake**

upstream: https://github.com/spmvg/nfoursid
pypi: https://pypi.org/project/nfoursid/
conda-forge: https://github.com/conda-forge/nfoursid-feedstock
dependencies: https://github.com/spmvg/nfoursid/blob/master/setup.cfg

- dependency for AnacondaRecipes/u8darts-feedstock#1

[PKG-3123]: https://anaconda.atlassian.net/browse/PKG-3123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by skupr-anaconda — APPROVED** [review]
LGTM

**Comment by skupr-anaconda** [comment]
Missing `abs.yaml`?

**Review by M-Waszkiewicz-Anaconda — APPROVED** [review]
LGTM

**Comment by lorepirri** [comment]
> Missing `abs.yaml`?

Yes sorry, I keep forgetting it... added.

**Pull request merged**
